module.exports = 
{


    successMessages:{
        USER_LOGIN: 'USER LOGGED IN SUCCESSFULLY',
        USER_SIGNED_UP:'USER SIGNED UP SUCCESSFULLY',
        PRODUCT_CREATED:'NEW PRODUCT ADDED TO INVENTORY'
    },
    FailureMessages:{
        PASSWORD_NOT_MATCHED:'PROVIDED PASSWORD IS INVALID',
        INVALID_CREDENTIALS:'INVALID CREDENTIALS',
        USERNAME_ALREADY_EXISTS:'USERNAME ALREADY EXISTS, PLEASE TRY TO LOGIN',
        SIGNUP_FAILED:'SIGNUP FAILED',
        UNAUTHORIZED_OPERATIONS:'UNAUTHORIZED OPERATIONS',
        UNAUTHENTICATED_USER:'USER IS NOT AUTHENTIC, PLEASE LOGIN',
        SOMETHING_WENT_WRONG:'SOMETHING WENT WRONG',
        FAILED_TO_FETCH_PRODUCTS:'FAILED TO FETCH PRODUCTS',
        TOKEN_EXPIRED:'TOKEN HAS BEEN EXPIRED PLEASE REFRESH TOKEN'
    }
}